### PR TITLE
Gaussian Smoothing

### PR DESCRIPTION
**Pull request by khilanravani**
The Gaussian smoothing operator is a 2-D convolution operator that is used to remove detail and noise in images. The idea of Gaussian smoothing is to use this 2-D distribution as a `point-spread' function, and this is achieved by convolution.

### CODE REVIEW

**Comment by khilanravani** [comment]
Sir, following are some outputs from gaussian smoothing : 
1) For gaussian-noised image : 
gsm_gsn_yield_ip
gsm_gsn_yield_op

2) For images with salt and pepper noise : 
gsm_s p_yield_ip
gsm_s p_yield_op

Using lena image: 
gsm_gsn1_output png
gsm_gsn1_input png

**Comment by khilanravani** [comment]
Both Inputs and outputs in the above comment

**Comment by khilanravani** [comment]
@lehins Sir, the conflicts in both the PR's are now resolved. Kindly review them.

**Comment by lehins** [comment]
@khilanravani, you again landed in a situation with conflicts in you PR, it's ok, but this means you aren't using `git` to the full potential. Here is an advice on how to deal with this without closing this PR: do a `git rebase` on the upsteam `master` and then do a `git push -f` to the same remote branch `new-gaussian-smoothing-filter`.

So, here is the free lesson :) If you had this branch `new-gaussian-smoothing-filter` rebased on the `log` branch. There would be no conflicts after I merged the `new-gaussian-smoothing-filter` branch. Of course you'd also need to specofy which PR I need to review first since there is a dependency.

**Comment by khilanravani** [comment]
@lehins Oh, sorry sir. I thought I resolved these. Yes sir, I'll ping you as soon as I resolve the conflicts.

**Pull request merged**
